### PR TITLE
M or G suffix now mandatory on apc.shm_size

### PR DESCRIPTION
**Pull request by caseyfw**

### CODE REVIEW

**Comment by caseyfw** [comment]
Bump.

**Comment by nickschuch** [comment]
Was fixed in here https://github.com/previousnext/puppet-webserver/pull/3

Ok for me to close this one?

**Comment by caseyfw** [comment]
Suffix still missing from manifests/php/apcu.pp

https://github.com/previousnext/puppet-webserver/blob/master/manifests/php/apcu.pp

**Comment by caseyfw** [comment]
PFWOAR!

**Comment by cafuego** [comment]
Timely, right?

**Pull request merged**
